import { takeMutationError } from "./feedback"
import { useState } from "react"
import { Plus, Trash2 } from "lucide-react"
import { FormActions } from "@/components/design-system"
import { ReferenceSection } from "@/components/reference-section"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { conkerClient } from "@/lib/api"
import { useConker, useConkerStore } from "@/lib/api/store"
import type { AgentTeamInput, AgentTeamRecord, TeamRoleInput } from "@/lib/api/agent-collaboration-types"
import { SearchableSelect } from "../../activity/searchable-select"
import { BudgetFields, MemoryFields, MultiChoice } from "./fields"
import { useCollaborationDraft } from "./use-draft"

const emptyTeam: AgentTeamInput = { name: "", objective: "", roles: [], handoffs: [], budget: { maxTurns: 8, maxTokens: 16000, maxCostCents: 0, maxHandoffs: 4 } }
const newRole = (): TeamRoleInput => ({ id: `role-${crypto.randomUUID().slice(0, 8)}`, name: "", agentId: "", instructions: "", toolIds: [], memory: { scope: "none", memoryIds: [] }, context: { mode: "task_only", sourceIds: [] }, budget: { maxTurns: 2, maxTokens: 2000, maxCostCents: 0 } })

export function TeamEditor({ record, onClose }: { record?: AgentTeamRecord; onClose: () => void }) {
  const { value, setValue, revision, stale, clear } = useCollaborationDraft(`team:${record?.id ?? "new"}`, record?.definition ?? emptyTeam, record?.revision)
  const data = useConker(data => data)
  const agents = data.agents.filter(agent => !agent.archivedAt && agent.configuration)
  const [error, setError] = useState("")
  const { mutate, pending } = useConkerStore()
  const updateRole = (id: string, patch: Partial<TeamRoleInput>) => setValue({ ...value, roles: value.roles.map(role => role.id === id ? { ...role, ...patch } : role) })
  const allocation = value.roles.reduce((total, role) => ({ turns: total.turns + role.budget.maxTurns, tokens: total.tokens + role.budget.maxTokens, cents: total.cents + role.budget.maxCostCents }), { turns: 0, tokens: 0, cents: 0 })
  return <form className="space-y-6" onSubmit={async event => {
    event.preventDefault()
    const saved = await mutate(() => record ? conkerClient.collaboration.updateTeam(record.id, value, revision!) : conkerClient.collaboration.createTeam(value), "Team configuration saved in preview. No work was started.")
    if (saved) { clear(); onClose() } else setError(takeMutationError())
  }}><div><h2 className="text-lg font-semibold">{record ? "Edit team" : "New team"}</h2><p className="mt-1 text-sm text-muted-foreground">Define responsibility, context and handoffs. Each role keeps its own scope.</p></div>
    <fieldset disabled={pending || !!record?.archivedAt} className="space-y-6">
      <div className="grid gap-5 lg:grid-cols-2"><div className="space-y-2"><Label htmlFor="team-name">Team name</Label><Input id="team-name" required maxLength={80} value={value.name} onChange={event => setValue({ ...value, name: event.target.value })} /></div><div className="space-y-2"><Label htmlFor="team-objective">Shared objective</Label><Textarea id="team-objective" required maxLength={2000} value={value.objective} onChange={event => setValue({ ...value, objective: event.target.value })} /></div></div>
      <ReferenceSection title="Total budget"><BudgetFields label="Limits for the whole team" value={value.budget} onChange={budget => setValue({ ...value, budget: { ...budget, maxHandoffs: value.budget.maxHandoffs } })} /><div className="max-w-sm space-y-2"><Label htmlFor="team-handoffs">Maximum handoffs</Label><Input id="team-handoffs" type="number" min={0} max={100} step={1} required value={value.budget.maxHandoffs} onChange={event => setValue({ ...value, budget: { ...value.budget, maxHandoffs: Number(event.target.value) } })} /></div><p className="text-xs text-muted-foreground">Allocated to roles: {allocation.turns} turns · {allocation.tokens.toLocaleString()} tokens · {allocation.cents} cents. Allocations must fit within the total.</p></ReferenceSection>
      <ReferenceSection title="Roles"><p className="text-sm text-muted-foreground">Choose configured agents. A role can narrow its agent’s tools and memory; it cannot borrow another role’s access.</p>{!agents.length && <p className="text-sm text-muted-foreground">Create and configure a specialist in the Agents tab first. Your team draft will be kept.</p>}
        <div className="space-y-4">{value.roles.map((role, index) => {
          const agent = agents.find(agent => agent.id === role.agentId)
          const allowedMemory = agent?.configuration?.memory
          return <details key={role.id} open={value.roles.length === 1 ? true : undefined} className="rounded-lg border p-4"><summary className="cursor-pointer rounded-sm text-sm font-medium focus-visible:outline-2 focus-visible:outline-ring">{role.name || `Role ${index + 1}`} · {agent?.name ?? "Choose an agent"}</summary><div className="mt-5 space-y-5">
            <div className="grid gap-4 lg:grid-cols-2"><div className="space-y-2"><Label htmlFor={`${role.id}-name`}>Role name</Label><Input id={`${role.id}-name`} required maxLength={80} value={role.name} onChange={event => updateRole(role.id, { name: event.target.value })} /></div><div className="space-y-2"><Label htmlFor={`${role.id}-agent`}>Assigned specialist</Label><SearchableSelect id={`${role.id}-agent`} label="Configured agents" value={role.agentId} options={agents.map(agent => ({ value: agent.id, label: agent.name }))} disabled={pending} onChange={agentId => updateRole(role.id, { agentId, toolIds: [], memory: { scope: "none", memoryIds: [] } })} /></div></div>
            <div className="space-y-2"><Label htmlFor={`${role.id}-instructions`}>Role instructions</Label><Textarea id={`${role.id}-instructions`} required maxLength={8000} value={role.instructions} onChange={event => updateRole(role.id, { instructions: event.target.value })} /><p className="text-xs text-muted-foreground">Supplementary role instructions. Changing the specialist clears this role’s tool and memory selections.</p></div>
            <div className="grid items-start gap-6 lg:grid-cols-2"><MultiChoice label="Role tools" value={role.toolIds} options={data.tools.filter(tool => agent?.configuration?.toolIds.includes(tool.id)).map(tool => ({ id: tool.id, label: `${tool.name} · v${tool.publishedVersion}` }))} onChange={toolIds => updateRole(role.id, { toolIds })} /><MemoryFields value={role.memory} allowedScopes={allowedMemory && allowedMemory.scope !== "none" ? ["none", allowedMemory.scope] : ["none"]} allowedIds={allowedMemory?.memoryIds ?? []} onChange={memory => updateRole(role.id, { memory })} /></div>
            <div className="space-y-3"><Label htmlFor={`${role.id}-context`}>Additional context</Label><Select value={role.context.mode} onValueChange={mode => updateRole(role.id, { context: { mode: mode as TeamRoleInput["context"]["mode"], sourceIds: mode === "selected" ? role.context.sourceIds : [] } })}><SelectTrigger id={`${role.id}-context`} className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="task_only">Task context only</SelectItem><SelectItem value="selected">Explicit conversation references</SelectItem></SelectContent></Select>{role.context.mode === "selected" && <MultiChoice label="Context sources" value={role.context.sourceIds} options={data.sessions.filter(session => !session.archived).map(session => ({ id: `session:${session.id}`, label: session.title }))} onChange={sourceIds => updateRole(role.id, { context: { ...role.context, sourceIds } })} />}<p className="text-xs text-muted-foreground">References only. No transcript is copied or handed off by this preview.</p></div>
            <BudgetFields label="Role budget" value={role.budget} onChange={budget => updateRole(role.id, { budget })} />
            <Button type="button" variant="outline" onClick={() => setValue({ ...value, roles: value.roles.filter(item => item.id !== role.id), handoffs: value.handoffs.filter(handoff => handoff.fromRoleId !== role.id && handoff.toRoleId !== role.id) })}><Trash2 />Remove role and its handoffs</Button>
          </div></details>
        })}</div><Button type="button" variant="outline" disabled={value.roles.length >= 12} onClick={() => setValue({ ...value, roles: [...value.roles, newRole()] })}><Plus />Add role</Button>
      </ReferenceSection>
      <ReferenceSection title="Handoffs"><p className="text-sm text-muted-foreground">Describe when one role passes its result to another. No credentials, memory scopes or grants travel with a handoff.</p><div className="space-y-4">{value.handoffs.map((handoff, index) => {
        const set = (patch: Partial<typeof handoff>) => setValue({ ...value, handoffs: value.handoffs.map(item => item.id === handoff.id ? { ...item, ...patch } : item) })
        return <fieldset key={handoff.id} className="space-y-4 rounded-lg border p-4"><legend className="px-1 text-sm font-medium">Handoff {index + 1}</legend><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor={`${handoff.id}-from`}>From role</Label><SearchableSelect id={`${handoff.id}-from`} label="Source roles" value={handoff.fromRoleId} options={value.roles.map(role => ({ value: role.id, label: role.name || "Unnamed role" }))} disabled={pending} onChange={fromRoleId => set({ fromRoleId })} /></div><div className="space-y-2"><Label htmlFor={`${handoff.id}-to`}>To role</Label><SearchableSelect id={`${handoff.id}-to`} label="Destination roles" value={handoff.toRoleId} options={value.roles.filter(role => role.id !== handoff.fromRoleId).map(role => ({ value: role.id, label: role.name || "Unnamed role" }))} disabled={pending} onChange={toRoleId => set({ toRoleId })} /></div></div><div className="space-y-2"><Label htmlFor={`${handoff.id}-condition`}>When should the handoff happen?</Label><Textarea id={`${handoff.id}-condition`} required maxLength={1000} value={handoff.condition} onChange={event => set({ condition: event.target.value })} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor={`${handoff.id}-payload`}>Content to pass</Label><Select value={handoff.payload} onValueChange={payload => set({ payload: payload as typeof handoff.payload })}><SelectTrigger id={`${handoff.id}-payload`} className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="result_only">Result only</SelectItem><SelectItem value="result_and_citations">Result and citations</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor={`${handoff.id}-limit`}>Maximum transfers</Label><Input id={`${handoff.id}-limit`} type="number" required min={1} max={100} step={1} value={handoff.maxTransfers} onChange={event => set({ maxTransfers: Number(event.target.value) })} /></div></div><Button type="button" variant="outline" onClick={() => setValue({ ...value, handoffs: value.handoffs.filter(item => item.id !== handoff.id) })}><Trash2 />Remove handoff</Button></fieldset>
      })}</div><Button type="button" variant="outline" disabled={value.roles.length < 2 || value.handoffs.length >= 30} onClick={() => setValue({ ...value, handoffs: [...value.handoffs, { id: `handoff-${crypto.randomUUID().slice(0, 8)}`, fromRoleId: value.roles[0].id, toRoleId: value.roles[1].id, condition: "", payload: "result_and_citations", maxTransfers: 1 }] })}><Plus />Add handoff</Button></ReferenceSection>
    </fieldset>
    {stale && <p role="alert" className="text-sm text-destructive">The team changed. Discard this draft and reopen it to edit the current revision.</p>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    <FormActions description="Draft kept across navigation. No executor connected."><Button type="button" variant="ghost" disabled={pending} onClick={() => { clear(); onClose() }}>Discard draft</Button><Button type="button" variant="outline" disabled={pending} onClick={onClose}>Back to teams</Button><Button type="submit" disabled={pending || stale || !value.roles.length || !!record?.archivedAt}>{pending ? "Saving…" : "Save team"}</Button></FormActions>
  </form>
}
