import { Link } from 'react-router-dom'
import type { ReactNode } from 'react'
import { OverlayBody } from '@/components/design-system/overlays'
import { ReferenceSection } from '@/components/reference-section'
import { Button } from '@/components/ui/button'
import { allowedGatewayTaskTransitions, type GatewayActivityEvent, type GatewayActivityRun, type GatewayTask, type GatewayTaskStatus } from '@/lib/gateway/activity'
import { activityLabel, eventLabel, isTerminalTask, taskStatusLabels } from './activity-state'

const conversationLink = (id: string) => `/chats?session=${encodeURIComponent(id)}`
const taskLink = (id: string) => `/activity?tab=tasks&task=${encodeURIComponent(id)}`
const runLink = (id: string) => `/activity?tab=runs&run=${encodeURIComponent(id)}`
export function GatewayTaskDetails({ task, disabled, onEdit, onReview, onArchive, onWork, workDisabled, workNotice, feedback }: { task: GatewayTask; disabled: boolean; onEdit: () => void; onReview: (status: GatewayTaskStatus) => void; onArchive: () => void; onWork?: () => void; workDisabled?: boolean; workNotice?: string; feedback?: ReactNode }) {
  const forgotten = task.contentStatus === 'forgotten'
  return <OverlayBody>
    {feedback}
    <ReferenceSection title="Status"><p className="text-sm">{taskStatusLabels[task.status]}{task.archivedAt ? ' · Archived' : ''}</p><p className="text-xs text-muted-foreground">Owner-reported · Companion · revision {task.revision}</p><p className="text-xs leading-5 text-muted-foreground">Task tracking does not start, stop or resume execution.</p></ReferenceSection>
    {forgotten ? <p className="text-sm text-muted-foreground">This task’s source was forgotten. Authored content and editing are unavailable.</p> : <><ReferenceSection title="Completion criteria"><ul className="list-disc space-y-2 pl-5 text-sm">{task.criteria.map(criterion => <li key={criterion.id}>{criterion.text}{task.completedCriterionIds.includes(criterion.id) ? ' · reviewed' : ''}</li>)}</ul></ReferenceSection>{task.statusNote && <ReferenceSection title="Latest owner review"><p className="whitespace-pre-wrap break-words text-sm">{task.statusNote}</p></ReferenceSection>}</>}
    <ReferenceSection title="Sources"><Button asChild variant="link" className="h-auto justify-start whitespace-normal p-0"><Link to={conversationLink(task.sessionId)}>Open source conversation</Link></Button>{task.parentTaskId && <Button asChild variant="link" className="h-auto justify-start whitespace-normal p-0"><Link to={taskLink(task.parentTaskId)}>Open parent task</Link></Button>}<p className="break-all text-xs text-muted-foreground">Task {task.id}</p></ReferenceSection>
    <ReferenceSection title="Linked runs">{task.runIds.length ? <ul className="space-y-2">{task.runIds.map(id => <li key={id}><Link className="break-all text-sm underline underline-offset-4" to={runLink(id)}>{id}</Link></li>)}</ul> : <p className="text-sm text-muted-foreground">No turns linked.</p>}</ReferenceSection>
    <ReferenceSection title="Task history"><ul className="space-y-2 text-xs">{task.changes.map(event => <li key={event.id}>{eventLabel(event)} · {new Date(event.occurredAt).toLocaleString()}{event.toStatus ? ` · ${activityLabel(event.toStatus)}` : ''}</li>)}</ul>{task.changesTruncated && <p className="text-xs text-muted-foreground">Showing the latest 100 changes.</p>}<Button asChild variant="link" className="h-auto justify-start p-0"><Link to={`/activity?tab=events&taskId=${encodeURIComponent(task.id)}`}>Inspect recorded events</Link></Button></ReferenceSection>
    {!forgotten && <div className="flex flex-wrap gap-2 border-t pt-4">{onWork && !task.archivedAt && !isTerminalTask(task) && <Button disabled={disabled || workDisabled} onClick={onWork}>Work on this task</Button>}{!task.archivedAt && !isTerminalTask(task) && <Button variant="outline" disabled={disabled} onClick={onEdit}>Edit task</Button>}{allowedGatewayTaskTransitions(task).map(status => <Button key={status} variant="outline" disabled={disabled} onClick={() => onReview(status)}>{status === 'planned' && isTerminalTask(task) ? 'Reopen tracking' : `Record ${taskStatusLabels[status].toLocaleLowerCase()}`}</Button>)}{workNotice && <p className="w-full text-xs text-muted-foreground">{workNotice}</p>}{(task.archivedAt || isTerminalTask(task)) && <Button variant="outline" disabled={disabled} onClick={onArchive}>{task.archivedAt ? 'Restore task' : 'Archive task'}</Button>}{!task.archivedAt && !isTerminalTask(task) && <p className="w-full text-xs text-muted-foreground">Complete or cancel tracking before archiving.</p>}</div>}
  </OverlayBody>
}

export function GatewayRunDetails({ run }: { run: GatewayActivityRun }) {
  return <OverlayBody><ReferenceSection title="Recorded runtime state"><p className="text-sm font-medium">{activityLabel(run.status)}</p><p className="break-all text-xs text-muted-foreground">{run.id}</p><p className="text-xs text-muted-foreground">Started {new Date(run.startedAt).toLocaleString()}{run.endedAt ? ` · End recorded ${new Date(run.endedAt).toLocaleString()}` : ''}</p><p className="text-xs leading-5 text-muted-foreground">An end timestamp can represent a parked turn. The recorded status determines whether work is resolved.</p></ReferenceSection>{run.contentStatus === 'forgotten' && <p className="text-sm text-muted-foreground">The source conversation was forgotten. This is a content-free record.</p>}{(run.provider || run.model) && <ReferenceSection title="Supplied model"><p className="break-words text-sm">{[run.provider, run.model].filter(Boolean).join(' / ')}</p></ReferenceSection>}{run.action && <ReferenceSection title="Recorded action"><p className="text-sm">{activityLabel(run.action.state)}</p><p className="break-all text-xs text-muted-foreground">{run.action.id}</p></ReferenceSection>}<ReferenceSection title="Sources"><Link className="text-sm underline underline-offset-4" to={conversationLink(run.sessionId)}>Open source conversation</Link>{run.messageRefs.length ? <div className="space-y-2">{run.messageRefs.map(ref => <Link key={ref.messageId} className="block text-sm underline underline-offset-4" to={`${conversationLink(run.sessionId)}&message=${encodeURIComponent(ref.messageId)}`}>{activityLabel(ref.purpose)} message · {ref.sequence}</Link>)}</div> : <p className="text-xs leading-5 text-muted-foreground">This older turn has no recorded message associations.</p>}{run.taskIds.map(id => <Link key={id} className="block break-all text-sm underline underline-offset-4" to={taskLink(id)}>Task {id}</Link>)}<Link className="block text-sm underline underline-offset-4" to={`/activity?tab=events&runId=${encodeURIComponent(run.id)}`}>Inspect this run’s events</Link></ReferenceSection></OverlayBody>
}

export function GatewayEventDetails({ event }: { event: GatewayActivityEvent }) {
  return <OverlayBody><ReferenceSection title="Recorded event"><p className="text-sm font-medium">{eventLabel(event)}</p><p className="text-xs text-muted-foreground">Sequence {event.sequence} · {new Date(event.occurredAt).toLocaleString()}</p>{(event.fromStatus || event.toStatus) && <p className="text-sm">{event.fromStatus ? activityLabel(event.fromStatus) : 'Created'} → {event.toStatus ? activityLabel(event.toStatus) : 'Unchanged'}</p>}{event.revision !== null && <p className="text-xs text-muted-foreground">Task revision {event.revision}</p>}<p className="break-all text-xs text-muted-foreground">{event.id}</p><p className="text-xs leading-5 text-muted-foreground">This event contains identifiers and state changes, without authored task or conversation text.</p></ReferenceSection><ReferenceSection title="Sources"><Link className="text-sm underline underline-offset-4" to={conversationLink(event.sessionId)}>Open conversation</Link>{event.taskId && <Link className="block text-sm underline underline-offset-4" to={taskLink(event.taskId)}>Open task</Link>}{event.runId && <Link className="block text-sm underline underline-offset-4" to={runLink(event.runId)}>Open recorded run</Link>}{event.actionId && <p className="break-all text-xs text-muted-foreground">Action {event.actionId}</p>}</ReferenceSection></OverlayBody>
}
