import { Link } from 'react-router-dom'
import type { ReactNode } from 'react'
import { OverlayBody } from '@/components/design-system/overlays'
import { ReferenceSection } from '@/components/reference-section'
import { Button } from '@/components/ui/button'
import { allowedGatewayTaskTransitions, type GatewayActivityEvent, type GatewayActivityRun, type GatewayTask, type GatewayTaskStatus } from '@/lib/gateway/activity'
import { isTerminalTask, taskStatusLabels } from './activity-state'
import { plainStatus } from './plain-status'

const conversationLink = (id: string) => `/chats?session=${encodeURIComponent(id)}`
const taskLink = (id: string) => `/activity?tab=tasks&task=${encodeURIComponent(id)}`
const runLink = (id: string) => `/activity?tab=runs&run=${encodeURIComponent(id)}`

export function GatewayTaskDetails({ task, disabled, onEdit, onReview, onArchive, onWork, workDisabled, workNotice, feedback }: { task: GatewayTask; disabled: boolean; onEdit: () => void; onReview: (status: GatewayTaskStatus) => void; onArchive: () => void; onWork?: () => void; workDisabled?: boolean; workNotice?: string; feedback?: ReactNode }) {
  const forgotten = task.contentStatus === 'forgotten'
  return <OverlayBody>
    {feedback}
    <ReferenceSection title="Status"><p className="text-sm">{taskStatusLabels[task.status]}{task.archivedAt ? ' · Archived' : ''}</p><p className="text-xs leading-5 text-muted-foreground">Task tracking does not start, stop or resume work.</p><details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Technical details</summary><p className="mt-1">Revision {task.revision}</p></details></ReferenceSection>
    {forgotten ? <p className="text-sm text-muted-foreground">This task's source was forgotten. Authored content and editing are unavailable.</p> : <><ReferenceSection title="Completion criteria"><ul className="list-disc space-y-2 pl-5 text-sm">{task.criteria.map(criterion => <li key={criterion.id}>{criterion.text}{task.completedCriterionIds.includes(criterion.id) ? ' - reviewed' : ''}</li>)}</ul></ReferenceSection>{task.statusNote && <ReferenceSection title="Latest owner review"><p className="whitespace-pre-wrap break-words text-sm">{task.statusNote}</p></ReferenceSection>}</>}
    <ReferenceSection title="Sources"><Button asChild variant="link" className="h-auto justify-start whitespace-normal p-0"><Link to={conversationLink(task.sessionId)}>Open source conversation</Link></Button>{task.parentTaskId && <Button asChild variant="link" className="h-auto justify-start whitespace-normal p-0"><Link to={taskLink(task.parentTaskId)}>Open parent task</Link></Button>}<details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Technical details</summary><p className="mt-1 break-all">Task {task.id}</p><p className="break-all">Conversation {task.sessionId}</p></details></ReferenceSection>
    <ReferenceSection title="Linked attempts">{task.runIds.length ? <ul className="space-y-2">{task.runIds.map((id, index) => <li key={id}><Link className="text-sm underline underline-offset-4" to={runLink(id)}>Attempt {index + 1}</Link></li>)}</ul> : <p className="text-sm text-muted-foreground">No attempts linked.</p>}</ReferenceSection>
    <ReferenceSection title="Task history"><ul className="space-y-2 text-xs">{task.changes.map(event => <li key={event.id}>{plainStatus(event.kind)} · {new Date(event.occurredAt).toLocaleString()}{event.toStatus ? ` - ${plainStatus(event.toStatus)}` : ''}</li>)}</ul>{task.changesTruncated && <p className="text-xs text-muted-foreground">Showing the latest 100 changes.</p>}<Button asChild variant="link" className="h-auto justify-start p-0"><Link to={`/activity?tab=events&taskId=${encodeURIComponent(task.id)}`}>Inspect technical history</Link></Button></ReferenceSection>
    {!forgotten && <div className="flex flex-wrap gap-2 border-t pt-4">{onWork && !task.archivedAt && !isTerminalTask(task) && <Button disabled={disabled || workDisabled} onClick={onWork}>Work on this task</Button>}{!task.archivedAt && !isTerminalTask(task) && <Button variant="outline" disabled={disabled} onClick={onEdit}>Edit task</Button>}{allowedGatewayTaskTransitions(task).map(status => <Button key={status} variant="outline" disabled={disabled} onClick={() => onReview(status)}>{status === 'planned' && isTerminalTask(task) ? 'Reopen tracking' : `Record ${taskStatusLabels[status].toLocaleLowerCase()}`}</Button>)}{workNotice && <p className="w-full text-xs text-muted-foreground">{workNotice}</p>}{(task.archivedAt || isTerminalTask(task)) && <Button variant="outline" disabled={disabled} onClick={onArchive}>{task.archivedAt ? 'Restore task' : 'Archive task'}</Button>}{!task.archivedAt && !isTerminalTask(task) && <p className="w-full text-xs text-muted-foreground">Complete or cancel tracking before archiving.</p>}</div>}
  </OverlayBody>
}

export function GatewayRunDetails({ run }: { run: GatewayActivityRun }) {
  return <OverlayBody><ReferenceSection title="Status"><p className="text-sm font-medium">{plainStatus(run.status)}</p><p className="text-xs text-muted-foreground">Started {new Date(run.startedAt).toLocaleString()}{run.endedAt ? ` · End recorded ${new Date(run.endedAt).toLocaleString()}` : ''}</p><p className="text-xs leading-5 text-muted-foreground">The status shown here determines whether this work is resolved.</p><details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Technical details</summary><p className="mt-1 break-all">{run.id}</p></details></ReferenceSection>{run.contentStatus === 'forgotten' && <p className="text-sm text-muted-foreground">The source conversation was forgotten. This is a content-free record.</p>}{(run.provider || run.model) && <ReferenceSection title="Answer model"><p className="break-words text-sm">{run.model || 'Not supplied'}</p><details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Technical details</summary><p className="mt-1 break-words">{[run.provider, run.model].filter(Boolean).join(' / ')}</p></details></ReferenceSection>}{run.action && <ReferenceSection title="Action"><p className="text-sm">{plainStatus(run.action.state)}</p><details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Technical details</summary><p className="mt-1 break-all">{run.action.id}</p></details></ReferenceSection>}<ReferenceSection title="Sources"><Link className="text-sm underline underline-offset-4" to={conversationLink(run.sessionId)}>Open source conversation</Link>{run.messageRefs.length ? <div className="space-y-2">{run.messageRefs.map((ref, index) => <Link key={ref.messageId} className="block text-sm underline underline-offset-4" to={`${conversationLink(run.sessionId)}&message=${encodeURIComponent(ref.messageId)}`}>Source message {index + 1}</Link>)}</div> : <p className="text-xs leading-5 text-muted-foreground">This older attempt has no recorded message links.</p>}{run.taskIds.map((id, index) => <Link key={id} className="block text-sm underline underline-offset-4" to={taskLink(id)}>Linked task {index + 1}</Link>)}<Link className="block text-sm underline underline-offset-4" to={`/activity?tab=events&runId=${encodeURIComponent(run.id)}`}>Inspect technical history</Link></ReferenceSection></OverlayBody>
}

export function GatewayEventDetails({ event }: { event: GatewayActivityEvent }) {
  return <OverlayBody><ReferenceSection title="Activity"><p className="text-sm font-medium">{plainStatus(event.kind)}</p><p className="text-xs text-muted-foreground">{new Date(event.occurredAt).toLocaleString()}</p>{(event.fromStatus || event.toStatus) && <p className="text-sm">{event.fromStatus ? plainStatus(event.fromStatus) : 'Created'} to {event.toStatus ? plainStatus(event.toStatus) : 'Unchanged'}</p>}<p className="text-xs leading-5 text-muted-foreground">This activity record contains state changes without authored task or conversation text.</p><details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Technical details</summary><p className="mt-1">Sequence {event.sequence}</p>{event.revision !== null && <p>Task revision {event.revision}</p>}<p className="break-all">{event.id}</p></details></ReferenceSection><ReferenceSection title="Sources"><Link className="text-sm underline underline-offset-4" to={conversationLink(event.sessionId)}>Open conversation</Link>{event.taskId && <Link className="block text-sm underline underline-offset-4" to={taskLink(event.taskId)}>Open task</Link>}{event.runId && <Link className="block text-sm underline underline-offset-4" to={runLink(event.runId)}>Open attempt</Link>}{event.actionId && <details className="text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">Technical details</summary><p className="mt-1 break-all">Action {event.actionId}</p></details>}</ReferenceSection></OverlayBody>
}
