import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Archive, History, Plus, RotateCcw, Save, Trash2, Users } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { CollectionLoading, CollectionPanel, CollectionRow, CollectionSection, ConfirmationDialog, FormActions, OverlayBody, PageHeader, WorkspaceAction, TaskDialogContent } from '@/components/design-system'
import { GatewayPageFrame } from './page-frame'
import type { AgentProfile, GatewayControlClient } from '@/lib/gateway/control'
import type { GatewayRuntimeClient, RuntimeSession } from '@/lib/gateway/runtime'
import { gatewayError } from '@/lib/gateway/transport'
import { GatewayTeamMutationError, type GatewayTeam, type GatewayTeamDefinition, type GatewayTeamRevision, type GatewayTeamSummary } from '@/lib/gateway/teams'

type Role = GatewayTeamDefinition['roles'][number]
const blank: GatewayTeamDefinition = { name: '', objective: '', roles: [], handoffs: [], budget: { maxTurns: 8, maxTokens: 16_000, maxCostCents: 0, maxHandoffs: 4 } }
const role = (): Role => ({ id: `role_${crypto.randomUUID().slice(0, 8)}`, name: '', agentId: '', instructions: '', toolIds: [], memory: { scope: 'none', memoryIds: [] }, context: { mode: 'task_only', sourceIds: [] }, budget: { maxTurns: 2, maxTokens: 2000, maxCostCents: 0 } })
const handoff = (roles: Role[]): GatewayTeamDefinition['handoffs'][number] => ({ id: `handoff_${crypto.randomUUID().slice(0, 8)}`, fromRoleId: roles[0].id, toRoleId: roles[1].id, condition: '', payload: 'result_and_citations', maxTransfers: 1 })
const mutationMessage = (error: unknown) => error instanceof GatewayTeamMutationError ? error.message : gatewayError(error).message

type AnyBudget = GatewayTeamDefinition['budget'] | Role['budget']
function BudgetFields({ value, onChange, handoffs = false }: { value: AnyBudget; onChange: (value: AnyBudget) => void; handoffs?: boolean }) {
  const fields = [{ key: 'maxTurns', label: 'Turns', min: 1, max: 200 }, { key: 'maxTokens', label: 'Tokens', min: 1, max: 1_000_000 }, { key: 'maxCostCents', label: 'Cost in cents', min: 0, max: 1_000_000 }] as const
  return <div className={`grid gap-4 ${handoffs ? 'sm:grid-cols-4' : 'sm:grid-cols-3'}`}>{fields.map(field => <div key={field.key} className="space-y-2"><Label>{field.label}</Label><Input type="number" required min={field.min} max={field.max} value={value[field.key]} onChange={event => onChange({ ...value, [field.key]: Number(event.target.value) })} /></div>)}{handoffs && 'maxHandoffs' in value && <div className="space-y-2"><Label>Handoffs</Label><Input type="number" required min={0} max={100} value={value.maxHandoffs} onChange={event => onChange({ ...value, maxHandoffs: Number(event.target.value) })} /></div>}</div>
}

function ChoiceList({ label, value, options, onChange }: { label: string; value: string[]; options: { id: string; label: string }[]; onChange: (value: string[]) => void }) {
  const unavailable = value.filter(id => !options.some(option => option.id === id))
  return <fieldset className="space-y-2"><legend className="text-sm font-medium">{label}</legend><div className="max-h-40 space-y-2 overflow-y-auto border p-3">{options.map(option => <label key={option.id} className="flex items-start gap-3 text-sm"><Checkbox checked={value.includes(option.id)} onCheckedChange={checked => onChange(checked === true ? [...value, option.id] : value.filter(id => id !== option.id))} /><span className="min-w-0 break-words">{option.label}</span></label>)}{unavailable.map(id => <label key={id} className="flex items-start gap-3 text-sm text-muted-foreground"><Checkbox checked onCheckedChange={() => onChange(value.filter(item => item !== id))} /><span className="break-all">Unavailable reference · {id}</span></label>)}{!options.length && !unavailable.length && <p className="text-xs text-muted-foreground">No available selections.</p>}</div></fieldset>
}

function TeamEditor({ initial, agents, sessions, onSave, onCancel }: { initial?: GatewayTeam; agents: AgentProfile[]; sessions: RuntimeSession[]; onSave: (definition: GatewayTeamDefinition) => Promise<void>; onCancel: () => void }) {
  const [value, setValue] = useState<GatewayTeamDefinition>(initial?.definition ?? blank)
  const [pending, setPending] = useState(false), [error, setError] = useState<string | null>(null)
  const updateRole = (id: string, patch: Partial<Role>) => setValue(current => ({ ...current, roles: current.roles.map(item => item.id === id ? { ...item, ...patch } : item) }))
  const allocation = value.roles.reduce((total, item) => ({ turns: total.turns + item.budget.maxTurns, tokens: total.tokens + item.budget.maxTokens, cost: total.cost + item.budget.maxCostCents }), { turns: 0, tokens: 0, cost: 0 })
  const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setError(null); try { await onSave(value) } catch (cause) { setError(mutationMessage(cause)) } finally { setPending(false) } }
  return <form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><OverlayBody><div className="space-y-7">
    <div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="team-name">Team name</Label><Input id="team-name" required maxLength={80} value={value.name} onChange={event => setValue({ ...value, name: event.target.value })} /></div><div className="space-y-2"><Label htmlFor="team-objective">Shared objective</Label><Textarea id="team-objective" required maxLength={2000} value={value.objective} onChange={event => setValue({ ...value, objective: event.target.value })} /></div></div>
    <fieldset className="space-y-4 border-t pt-5"><legend className="pr-3 text-sm font-semibold">Total limits</legend><BudgetFields handoffs value={value.budget} onChange={budget => setValue({ ...value, budget: budget as GatewayTeamDefinition['budget'] })} /><p className="text-xs text-muted-foreground">Allocated: {allocation.turns} turns · {allocation.tokens.toLocaleString()} tokens · {allocation.cost} cents. Zero cents prevents paid use.</p></fieldset>
    <section className="space-y-4" aria-labelledby="team-roles"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="team-roles" className="text-sm font-semibold">Roles</h3><p className="mt-1 text-xs text-muted-foreground">Each role narrows one saved agent. It cannot borrow another role’s tools or memory.</p></div><Button type="button" variant="outline" size="sm" disabled={value.roles.length >= 12} onClick={() => setValue({ ...value, roles: [...value.roles, role()] })}><Plus />Add role</Button></div>
      <div className="space-y-4">{value.roles.map((item, index) => { const selected = agents.find(agent => agent.id === item.agentId), allowedMemory = selected?.configuration.memory; return <details key={item.id} open={value.roles.length === 1 || undefined} className="border p-4"><summary className="cursor-pointer text-sm font-medium">{item.name || `Role ${index + 1}`} · {selected?.configuration.name ?? 'Choose an agent'}</summary><div className="mt-5 space-y-5">
        <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Role name</Label><Input required maxLength={80} value={item.name} onChange={event => updateRole(item.id, { name: event.target.value })} /></div><div className="space-y-2"><Label>Assigned agent</Label><Select value={item.agentId} onValueChange={agentId => updateRole(item.id, { agentId, toolIds: [], memory: { scope: 'none', memoryIds: [] } })}><SelectTrigger className="w-full"><SelectValue placeholder="Choose an agent" /></SelectTrigger><SelectContent>{agents.filter(agent => agent.archived_at === null).map(agent => <SelectItem key={agent.id} value={agent.id}>{agent.configuration.name}</SelectItem>)}</SelectContent></Select></div></div>
        <div className="space-y-2"><Label>Role instructions</Label><Textarea required maxLength={8000} className="min-h-28" value={item.instructions} onChange={event => updateRole(item.id, { instructions: event.target.value })} /></div>
        <div className="grid items-start gap-5 sm:grid-cols-2"><ChoiceList label="Agent tools" value={item.toolIds} options={(selected?.configuration.toolIds ?? []).map(id => ({ id, label: id }))} onChange={toolIds => updateRole(item.id, { toolIds })} /><div className="space-y-3"><Label>Memory scope</Label><Select value={item.memory.scope} onValueChange={(scope: Role['memory']['scope']) => updateRole(item.id, { memory: { scope, memoryIds: scope === 'selected' ? item.memory.memoryIds : [] } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">No memory</SelectItem>{allowedMemory?.scope === 'conversation' && <SelectItem value="conversation">Conversation context</SelectItem>}{allowedMemory?.scope === 'selected' && <SelectItem value="selected">Selected records</SelectItem>}</SelectContent></Select>{item.memory.scope === 'selected' && <ChoiceList label="Memory records" value={item.memory.memoryIds} options={(allowedMemory?.memoryIds ?? []).map(id => ({ id, label: id }))} onChange={memoryIds => updateRole(item.id, { memory: { ...item.memory, memoryIds } })} />}</div></div>
        <div className="space-y-3"><Label>Additional context</Label><Select value={item.context.mode} onValueChange={(mode: Role['context']['mode']) => updateRole(item.id, { context: { mode, sourceIds: mode === 'selected' ? item.context.sourceIds : [] } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="task_only">Task context only</SelectItem><SelectItem value="selected">Selected conversations</SelectItem></SelectContent></Select>{item.context.mode === 'selected' && <ChoiceList label="Conversation references" value={item.context.sourceIds} options={sessions.filter(session => session.status !== 'forgotten').map(session => ({ id: `session:${session.id}`, label: session.title || 'Untitled conversation' }))} onChange={sourceIds => updateRole(item.id, { context: { ...item.context, sourceIds } })} />}</div>
        <BudgetFields value={item.budget} onChange={budget => updateRole(item.id, { budget: budget as Role['budget'] })} />
        <Button type="button" variant="outline" onClick={() => setValue(current => ({ ...current, roles: current.roles.filter(role => role.id !== item.id), handoffs: current.handoffs.filter(edge => edge.fromRoleId !== item.id && edge.toRoleId !== item.id) }))}><Trash2 />Remove role</Button>
      </div></details> })}</div>
    </section>
    <section className="space-y-4" aria-labelledby="team-handoffs"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="team-handoffs" className="text-sm font-semibold">Handoffs</h3><p className="mt-1 text-xs text-muted-foreground">Only the declared result travels. Credentials, memory scope, and authority never transfer.</p></div><Button type="button" variant="outline" size="sm" disabled={value.roles.length < 2 || value.handoffs.length >= 30} onClick={() => setValue({ ...value, handoffs: [...value.handoffs, handoff(value.roles)] })}><Plus />Add handoff</Button></div>
      <div className="space-y-4">{value.handoffs.map((edge, index) => { const update = (patch: Partial<typeof edge>) => setValue(current => ({ ...current, handoffs: current.handoffs.map(item => item.id === edge.id ? { ...item, ...patch } : item) })); return <fieldset key={edge.id} className="space-y-4 border p-4"><legend className="px-1 text-sm font-medium">Handoff {index + 1}</legend><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>From</Label><Select value={edge.fromRoleId} onValueChange={fromRoleId => update({ fromRoleId })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{value.roles.map(role => <SelectItem key={role.id} value={role.id}>{role.name || role.id}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>To</Label><Select value={edge.toRoleId} onValueChange={toRoleId => update({ toRoleId })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{value.roles.filter(role => role.id !== edge.fromRoleId).map(role => <SelectItem key={role.id} value={role.id}>{role.name || role.id}</SelectItem>)}</SelectContent></Select></div></div><div className="space-y-2"><Label>Handoff condition</Label><Textarea required maxLength={1000} value={edge.condition} onChange={event => update({ condition: event.target.value })} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Content</Label><Select value={edge.payload} onValueChange={(payload: typeof edge.payload) => update({ payload })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="result_only">Result only</SelectItem><SelectItem value="result_and_citations">Result and citations</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Maximum transfers</Label><Input type="number" required min={1} max={100} value={edge.maxTransfers} onChange={event => update({ maxTransfers: Number(event.target.value) })} /></div></div><Button type="button" variant="outline" onClick={() => setValue(current => ({ ...current, handoffs: current.handoffs.filter(item => item.id !== edge.id) }))}><Trash2 />Remove handoff</Button></fieldset> })}</div>
    </section>
  </div></OverlayBody><FormActions inset description={error ? <span role="alert" className="text-destructive">{error}</span> : 'Configuration only. Saving never prepares or starts a team run.'}><Button type="button" variant="outline" disabled={pending} onClick={onCancel}>Cancel</Button><Button type="submit" disabled={pending || !value.name.trim() || !value.objective.trim() || !value.roles.length}><Save />{pending ? 'Saving…' : 'Save team'}</Button></FormActions></form>
}

function TeamDefinition({ value, agents }: { value: GatewayTeamDefinition; agents: AgentProfile[] }) {
  return <div className="space-y-5"><div><h3 className="text-base font-semibold">{value.name}</h3><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{value.objective}</p></div><p className="text-xs text-muted-foreground">Maximum {value.budget.maxTurns} turns · {value.budget.maxTokens.toLocaleString()} tokens · {value.budget.maxCostCents} cents · {value.budget.maxHandoffs} handoffs</p><div className="divide-y border-y">{value.roles.map(role => <div key={role.id} className="py-4"><p className="text-sm font-medium">{role.name} · {agents.find(agent => agent.id === role.agentId)?.configuration.name ?? role.agentId}</p><p className="mt-1 whitespace-pre-wrap text-sm">{role.instructions}</p><p className="mt-2 text-xs text-muted-foreground">{role.toolIds.length} tools · {role.memory.scope} memory · {role.context.mode.replace('_', ' ')} · {role.budget.maxTurns} turns</p></div>)}</div>{value.handoffs.length > 0 && <div className="space-y-3"><h4 className="text-sm font-semibold">Handoffs</h4>{value.handoffs.map(edge => <div key={edge.id} className="text-sm"><p className="font-medium">{value.roles.find(role => role.id === edge.fromRoleId)?.name} → {value.roles.find(role => role.id === edge.toRoleId)?.name}</p><p className="mt-1 text-muted-foreground">{edge.condition} · {edge.payload.replaceAll('_', ' ')} · up to {edge.maxTransfers}</p></div>)}</div>}</div>
}

export function GatewayTeamsWorkspace({ control, runtime }: { control: GatewayControlClient; runtime: GatewayRuntimeClient }) {
  const [params, setParams] = useSearchParams(), selectedId = params.get('team')
  const [teams, setTeams] = useState<Awaited<ReturnType<typeof control.teams.list>>['results'] | null>(null), [agents, setAgents] = useState<AgentProfile[]>([]), [sessions, setSessions] = useState<RuntimeSession[]>([])
  const [query, setQuery] = useState(''), [error, setError] = useState<string | null>(null), [selected, setSelected] = useState<GatewayTeam | null>(null), [history, setHistory] = useState<GatewayTeamRevision | null>(null)
  const [editing, setEditing] = useState<GatewayTeam | 'new' | null>(null), [archive, setArchive] = useState<GatewayTeam | null>(null), [pending, setPending] = useState(false)
  useEffect(() => {
    let active = true
    Promise.all([control.teams.list(), control.agents(), runtime.listSessions()]).then(([page, profiles, chats]) => {
      if (active) { setTeams(page.results); setAgents(profiles); setSessions(chats) }
    }).catch(cause => { if (active) setError(gatewayError(cause).message) })
    return () => { active = false }
  }, [control, runtime])
  useEffect(() => {
    if (!selectedId || !/^team_[0-9a-f]{32}$/.test(selectedId)) return
    const controller = new AbortController()
    control.teams.get(selectedId, controller.signal).then(value => { if (!controller.signal.aborted) setSelected(value) }).catch(cause => { if (!controller.signal.aborted) setError(gatewayError(cause).message) })
    return () => controller.abort()
  }, [control, selectedId])
  const summaryOf = (saved: GatewayTeam): GatewayTeamSummary => ({ schemaVersion: 1, id: saved.id, revision: saved.revision, name: saved.name, archived_at: saved.archived_at, created_at: saved.created_at, updated_at: saved.updated_at, authority: 'none', execution: 'configuration-only', contentIncluded: false, reference_validation: 'external-references-unverified' })
  const save = async (definition: GatewayTeamDefinition) => { const saved = editing === 'new' ? await control.teams.create(definition) : await control.teams.update(editing!.id, definition, editing!.revision); setTeams(current => current ? [...current.filter(item => item.id !== saved.id), summaryOf(saved)].sort((a, b) => a.name.localeCompare(b.name)) : current); setSelected(saved); setEditing(null); const next = new URLSearchParams(params); next.set('team', saved.id); setParams(next) }
  const setArchived = async () => { if (!archive) return; setPending(true); setError(null); try { const saved = await control.teams.setArchived(archive.id, archive.archived_at === null, archive.revision); setSelected(saved); setTeams(current => current?.map(item => item.id === saved.id ? summaryOf(saved) : item) ?? current); setArchive(null) } catch (cause) { setError(mutationMessage(cause)) } finally { setPending(false) } }
  const inspectRevision = async (number: number) => { if (!selected) return; setPending(true); setError(null); try { setHistory(await control.teams.revision(selected.id, number)) } catch (cause) { setError(gatewayError(cause).message) } finally { setPending(false) } }
  const visible = useMemo(() => (teams ?? []).filter(item => item.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [teams, query])
  return <GatewayPageFrame><div className="space-y-6"><PageHeader actionsOnly title="Teams" density="compact" actions={<WorkspaceAction onClick={() => setEditing('new')}><Plus />New team</WorkspaceAction>} />
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    {!teams && !error ? <CollectionLoading label="Loading teams" /> : <CollectionPanel query={query} onQueryChange={setQuery} label="Search teams" placeholder="Search teams" count={visible.length} unit={visible.length === 1 ? 'team' : 'teams'} emptyTitle={query ? 'No matching teams' : 'No teams yet'} emptyDescription={query ? 'Try another team name or clear the search.' : 'Compose saved agents into bounded roles and declared handoffs. Definitions grant no authority and start no work.'} emptyAction={<Button onClick={() => setEditing('new')}><Plus />New team</Button>} icon={<Users />}><div className="space-y-5">{visible.some(item => item.archived_at === null) && <CollectionSection title="Active teams">{visible.filter(item => item.archived_at === null).map(item => <CollectionRow key={item.id} to={`/agents?tab=teams&team=${item.id}`} title={item.name} description="Configuration only" leading={<span className="flex size-8 items-center justify-center rounded-lg border"><Users className="size-4" /></span>} trailing={<span>Revision {item.revision}</span>} />)}</CollectionSection>}{visible.some(item => item.archived_at !== null) && <CollectionSection title="Archived">{visible.filter(item => item.archived_at !== null).map(item => <CollectionRow key={item.id} to={`/agents?tab=teams&team=${item.id}`} title={item.name} description="Archived configuration" leading={<span className="flex size-8 items-center justify-center rounded-lg border"><Archive className="size-4" /></span>} trailing={<span>Revision {item.revision}</span>} />)}</CollectionSection>}</div></CollectionPanel>}
  </div>
  <Dialog open={Boolean(selectedId) && editing === null} onOpenChange={open => { if (!open) { const next = new URLSearchParams(params); next.delete('team'); setParams(next); setSelected(null) } }}><TaskDialogContent title={selected?.definition.name ?? 'Team'} description="Durable configuration and immutable revision history" size="wide">{selected ? <div className="flex min-h-0 flex-1 flex-col"><OverlayBody><div className="space-y-6"><div className="flex flex-wrap items-center gap-2"><Badge variant={selected.archived_at ? 'secondary' : 'outline'}>{selected.archived_at ? 'Archived' : 'Configuration only'}</Badge><Badge variant="outline">{selected.agentReferenceState.replaceAll('-', ' ')}</Badge><span className="text-xs text-muted-foreground">Revision {selected.revision}</span></div><TeamDefinition value={selected.definition} agents={agents} /><section className="space-y-3 border-t pt-5"><h3 className="text-sm font-semibold">Revision history</h3><HistoryList control={control} team={selected} pending={pending} onInspect={inspectRevision} /></section>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</div></OverlayBody><FormActions inset description="No preparation or execution endpoint is exposed here."><Button variant="outline" disabled={pending} onClick={() => setArchive(selected)}>{selected.archived_at ? <RotateCcw /> : <Archive />}{selected.archived_at ? 'Restore' : 'Archive'}</Button>{!selected.archived_at && <Button disabled={pending} onClick={() => setEditing(selected)}>Edit team</Button>}</FormActions></div> : <p role="status" className="p-6 text-sm text-muted-foreground">Loading team…</p>}</TaskDialogContent></Dialog>
  <Dialog open={editing !== null} onOpenChange={open => !open && setEditing(null)}><TaskDialogContent title={editing === 'new' ? 'New team' : 'Edit team'} description="Define roles, limits, context, and explicit handoffs." size="wide"><TeamEditor initial={editing === 'new' ? undefined : editing ?? undefined} agents={agents} sessions={sessions} onSave={save} onCancel={() => setEditing(null)} /></TaskDialogContent></Dialog>
  <Dialog open={history !== null} onOpenChange={open => !open && setHistory(null)}><TaskDialogContent title={history ? `${history.name} · revision ${history.revision}` : 'Historical team'} description="Immutable historical definition; current agent availability is not inferred." size="wide">{history && <OverlayBody><TeamDefinition value={history.definition} agents={agents} /></OverlayBody>}</TaskDialogContent></Dialog>
  <ConfirmationDialog open={archive !== null} onOpenChange={open => !open && setArchive(null)} title={archive?.archived_at ? `Restore ${archive?.definition.name}?` : `Archive ${archive?.definition.name}?`} description={archive?.archived_at ? 'Current agent references and narrowed selections will be revalidated before the team returns to active configuration.' : 'The team and its immutable revisions remain available, but it leaves the active list.'} actionLabel={archive?.archived_at ? 'Restore team' : 'Archive team'} actionVariant={archive?.archived_at ? 'default' : 'destructive'} pending={pending} error={error} onConfirm={() => void setArchived()} />
  </GatewayPageFrame>
}

function HistoryList({ control, team, pending, onInspect }: { control: GatewayControlClient; team: GatewayTeam; pending: boolean; onInspect: (revision: number) => void }) {
  const [rows, setRows] = useState<number[] | null>(null)
  useEffect(() => { let active = true; control.teams.history(team.id).then(value => active && setRows(value.results.map(item => item.revision).reverse())).catch(() => active && setRows([])); return () => { active = false } }, [control, team.id, team.revision])
  if (rows === null) return <p className="text-sm text-muted-foreground">Loading revisions…</p>
  return rows.length ? <div className="flex flex-wrap gap-2">{rows.map(number => <Button key={number} variant="outline" size="sm" disabled={pending} onClick={() => onInspect(number)}><History />Revision {number}</Button>)}</div> : <p className="text-sm text-muted-foreground">Revision history is unavailable.</p>
}
