// Run against npm run dev (or dev:sandbox on restricted Windows).
// Requires Playwright; PLAYWRIGHT_MODULE may point to an existing installation.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const assert = require('node:assert/strict')
const { mkdir } = require('node:fs/promises')
const base = process.env.CONKER_URL || 'http://localhost:5173'

async function run() {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
  const errors = []
  const outgoing = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  page.on('request', request => { if (/gate\.example|pi\.example/.test(request.url())) outgoing.push(request.url()) })
  page.setDefaultTimeout(10000)
  const goto = async route => { await page.goto(base + route); await page.locator('h1').waitFor() }
  const navigate = async route => { await page.locator(`[data-sidebar="sidebar"] a[href="${route}"]`).first().click(); await page.waitForURL(base + route) }
  const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `Horizontal overflow: ${page.url()}`)
  try {
    await mkdir('.cache/review', { recursive: true })
    const routes = ['/', '/chat', '/chat/week', '/chat/server', '/chat/reading', '/chat/judo', '/chat/dashboard', '/inbox', '/inbox/coach', '/memory', '/journal', '/agents', '/tools', '/jobs', '/system', '/terminal', '/companion', '/settings', '/not-a-route']
    let left
    for (const route of routes) {
      await goto(route)
      const heading = await page.locator('h1').boundingBox()
      left ??= heading.x
      assert.equal(heading.x, left, `Heading alignment: ${route}`)
      await noOverflow()
      assert.equal(await page.getByRole('button', { name: 'Customize theme and layout' }).count(), 0)
    }
    console.log('PASS all dashboard routes share their heading grid; no horizontal overflow')

    await goto('/companion')
    await page.getByLabel('Name', { exact: true }).fill('Hazel')
    await page.getByLabel('Status / mood line').fill('Curious and ready')
    await page.getByRole('radio', { name: /Direct/ }).check()
    await page.getByRole('button', { name: 'Cat', exact: true }).click()
    await page.getByRole('button', { name: 'Graphite', exact: true }).click()
    await page.getByLabel('happy', { exact: true }).click()
    await page.getByRole('option', { name: 'Cat face' }).click()
    await page.getByRole('button', { name: 'Save character', exact: true }).click()
    await page.getByText('Saved in this preview', { exact: true }).waitFor()
    await page.getByRole('link', { name: 'Talk to Hazel' }).click()
    await page.getByText('Curious and ready · fixture').waitFor()
    await page.getByText('Be brief and practical. Lead with the answer, then the next step.').waitFor()
    const thread = await page.getByLabel('Conversation thread').boundingBox()
    assert.ok(thread.width > 1000, 'Conversation uses content width')
    const input = page.getByRole('textbox', { name: 'Message Hazel' })
    await input.fill('A test message')
    await input.press('Shift+Enter')
    await input.press('x')
    assert.match(await input.inputValue(), /\nx$/)
    await input.press('Enter')
    await page.getByText('A test message\nx', { exact: true }).waitFor()
    assert.equal(await input.inputValue(), '')
    await navigate('/chat')
    await page.getByRole('link', { name: 'Make room for the week', exact: true }).click()
    await page.getByText('A test message\nx', { exact: true }).waitFor()
    await page.screenshot({ path: '.cache/review/conversation.png', fullPage: true })
    console.log('PASS character identity, style, portrait, and sent messages survive navigation')

    await navigate('/inbox')
    await page.getByRole('link', { name: /Ask coach about Friday/ }).click()
    await page.getByRole('button', { name: 'Approve once' }).click()
    await page.getByText('Approved once', { exact: true }).first().waitFor()
    assert.equal(await page.getByRole('button', { name: 'Approve once' }).count(), 0)
    await navigate('/jobs')
    await page.getByRole('button', { name: /Actions for/ }).first().click()
    await page.getByRole('menuitem', { name: 'Pause', exact: true }).click()
    await page.getByText('Schedule changed in the fixture only.', { exact: false }).waitFor()
    console.log('PASS approvals and jobs write through the shared client')

    await navigate('/settings')
    await page.getByRole('combobox', { name: 'Tweakcn preset' }).click()
    await page.getByRole('option').nth(1).click()
    await page.getByRole('button', { name: 'Radius 0.75', exact: true }).press('Enter')
    assert.equal(await page.evaluate(() => document.documentElement.style.getPropertyValue('--radius')), '0.75rem')
    await navigate('/terminal')
    await page.getByRole('button', { name: 'Switch to light mode' }).click()
    await page.waitForFunction(() => document.documentElement.classList.contains('light'))
    assert.equal(await page.locator('.terminal-surface').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(10, 10, 10)')
    assert.equal(await page.evaluate(() => document.documentElement.style.getPropertyValue('--radius')), '0.75rem')
    await navigate('/settings')
    await page.getByRole('tab', { name: 'Layout', exact: true }).click()
    for (const name of ['Right', 'Floating', 'Icon', 'None', 'Left', 'Inset', 'Off Canvas']) {
      await page.getByRole('button', { name, exact: true }).press('Enter')
      assert.equal(await page.getByRole('button', { name, exact: true }).getAttribute('aria-pressed'), 'true')
      await noOverflow()
    }
    await page.getByRole('button', { name: 'Reset layout' }).click()
    await page.getByRole('tab', { name: 'Appearance', exact: true }).click()
    await page.getByRole('button', { name: 'Reset appearance' }).click()
    await page.getByRole('button', { name: 'Switch to dark mode' }).click()
    await page.waitForFunction(() => document.documentElement.classList.contains('dark'))
    await page.screenshot({ path: '.cache/review/settings.png', fullPage: true })
    await page.keyboard.press('Control+k')
    await page.getByRole('dialog').waitFor()
    await page.getByRole('option', { name: 'Home', exact: true }).click()
    await page.waitForURL(base + '/')
    console.log('PASS theme, radius, light terminal, all layout choices, and command navigation')

    await goto('/setup')
    assert.equal(await page.locator('[data-sidebar="sidebar"]').count(), 0)
    await page.getByLabel('What should we call you?').fill('Sam')
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByLabel('Password', { exact: true }).fill('preview-password-123')
    await page.getByLabel('Confirm password').fill('different-password')
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByRole('alert').filter({ hasText: 'don’t match' }).waitFor()
    await page.getByLabel('Confirm password').fill('preview-password-123')
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.locator('#memorygate-endpoint').fill('https://memorygate.example')
    await page.locator('#memorygate-key').fill('preview-key-123')
    await page.getByRole('button', { name: 'Finish setup preview' }).click()
    await page.getByRole('heading', { name: 'Preview ready' }).waitFor()
    await page.getByRole('button', { name: 'Explore fixture dashboard' }).click()
    await page.waitForURL(base + '/')
    await navigate('/settings')
    await page.getByRole('tab', { name: 'Connections' }).click()
    assert.equal(await page.locator('#memorygate-endpoint').inputValue(), 'https://memorygate.example')
    const storage = await page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }))
    assert.ok(!storage.includes('preview-password-123') && !storage.includes('preview-key-123'), 'Secrets must not be persisted')
    assert.equal(outgoing.length, 0, 'Fixture must never contact services')
    await goto('/login')
    assert.equal(await page.locator('[data-sidebar="sidebar"]').count(), 0)
    await page.getByLabel('Dashboard password').fill('any-password')
    await page.getByRole('button', { name: 'Preview sign in' }).click()
    await page.getByRole('status').filter({ hasText: 'Authentication is not connected' }).waitFor()
    assert.equal(await page.getByLabel('Dashboard password').inputValue(), '')
    assert.equal(new URL(page.url()).pathname, '/login')
    console.log('PASS setup validation, shared connection draft, no secret persistence or fake login')

    await page.setViewportSize({ width: 390, height: 844 })
    for (const route of [...routes, '/setup', '/login']) { await goto(route); await noOverflow() }
    await goto('/companion')
    await page.screenshot({ path: '.cache/review/studio-mobile.png', fullPage: true })
    await page.setViewportSize({ width: 1920, height: 1080 })
    await goto('/')
    assert.ok((await page.getByLabel('Conversation thread').boundingBox()).width <= 1280)
    assert.deepEqual(errors, [], 'Browser console errors')
    console.log('PASS all mobile routes and wide desktop content cap; zero browser errors')
  } finally { await browser.close() }
}
run().catch(error => { console.error(error); process.exitCode = 1 })
