const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { webcrypto } = require('node:crypto')
const root = path.resolve(__dirname, '..')
const ts = require(path.join(root, 'node_modules/typescript'))
globalThis.crypto ??= webcrypto
const cache = new Map()
function load(relative) {
  if (cache.has(relative)) return cache.get(relative).exports
  const source = fs.readFileSync(path.join(root, relative), 'utf8').replaceAll('import.meta.env', '({})')
  const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } })
  const module = { exports: {} }; cache.set(relative, module)
  new Function('require', 'module', 'exports', compiled.outputText)(request => {
    assert.ok(request.startsWith('.'), `Unexpected external dependency: ${request}`)
    return load(`${path.posix.normalize(path.posix.join(path.posix.dirname(relative), request))}.ts`)
  }, module, module.exports)
  return module.exports
}
async function main() {
  const { createFixtureClient } = load('src/lib/api/fixture-adapter.ts')
  const client = createFixtureClient()
  await client.updateConversation('companion', { privacy: { memoryDisabled: true }, presentationMode: 'character' })
  const first = await client.calls.start('companion')
  assert.equal(first.mode, 'character')
  assert.deepEqual(first.privacy, { memory: true, harness: false })
  assert.equal(first.channels.microphone, false, 'starting never requests/claims microphone capture')
  assert.equal(first.channels.camera, false)
  assert.equal((await client.calls.start('another-conversation')).id, first.id, 'only one active call')
  const changed = await client.calls.update(first.id, { channels: { microphone: true, voice: false, captions: false }, privacy: { harness: true }, mode: 'focus' })
  assert.equal(changed.channels.keyboard, true)
  assert.equal(changed.channels.camera, false)
  assert.equal(changed.channels.avatar, true)
  assert.equal(changed.channels.voice, false)
  assert.equal(changed.privacy.memory, true)
  assert.equal((await client.load()).conversations.companion.privacy.harnessDisabled, false, 'call privacy does not silently mutate chat')
  await assert.rejects(client.calls.update(first.id, { modelId: 'unknown' }), /enabled model/)
  await assert.rejects(client.calls.send(first.id, ' '.repeat(10), new AbortController().signal, () => {}), /Enter/)
  await assert.rejects(client.calls.send(first.id, 'x'.repeat(4001), new AbortController().signal, () => {}), /4,000/)
  const cancel = new AbortController()
  const stopped = await client.calls.send(first.id, 'Please stop this sample.', cancel.signal, () => cancel.abort())
  assert.equal(stopped.phase, 'ready')
  assert.equal(stopped.events.filter(event => event.kind === 'assistant').length, 0, 'interrupt prevents a late answer')
  assert.ok(stopped.events.some(event => event.text === 'Response interrupted'))
  const phases = []
  const answered = await client.calls.send(first.id, 'Test typed call without voice.', new AbortController().signal, value => phases.push(value.phase))
  assert.deepEqual(phases, ['thinking', 'responding'])
  assert.equal(answered.events.filter(event => event.kind === 'assistant').length, 1)
  assert.match(answered.events.at(-1).text, /sample response/)
  const late = new AbortController()
  const sending = client.calls.send(first.id, 'End during a response.', late.signal, () => {})
  late.abort()
  const ended = await client.calls.end(first.id)
  assert.equal(ended.phase, 'ended'); assert.equal(ended.channels.microphone, false); assert.equal(ended.channels.camera, false)
  const next = await client.calls.start('companion')
  assert.notEqual(next.id, first.id)
  assert.equal((await sending).id, first.id, 'old response cannot replace the next call')
  assert.equal(next.events.length, 1)
  await assert.rejects(client.calls.update(first.id, { mode: 'focus' }), /ended/)
  next.events[0].text = 'changed externally'
  assert.notEqual((await client.calls.start('companion')).events[0].text, 'changed externally', 'call snapshots are isolated')
  console.log('Call checks passed: single-session lifecycle, independent channels, inherited privacy, model validation, typed turns, interruptions, late response isolation, and hang-up.')
}
main().catch(error => { console.error(error); process.exitCode = 1 })
