import { lazy } from 'react'

export const BookmarkIcon = lazy(() => import('@animateicons/react/lucide/bookmark-icon').then(module => ({ default: module.BookmarkIcon })))
export const BrainIcon = lazy(() => import('@animateicons/react/lucide/brain-icon').then(module => ({ default: module.BrainIcon })))
export const CameraIcon = lazy(() => import('@animateicons/react/lucide/camera-icon').then(module => ({ default: module.CameraIcon })))
export const ClockIcon = lazy(() => import('@animateicons/react/lucide/clock-icon').then(module => ({ default: module.ClockIcon })))
export const CpuIcon = lazy(() => import('@animateicons/react/lucide/cpu-icon').then(module => ({ default: module.CpuIcon })))
export const EllipsisIcon = lazy(() => import('@animateicons/react/lucide/ellipsis-icon').then(module => ({ default: module.EllipsisIcon })))
export const EyeOffIcon = lazy(() => import('@animateicons/react/lucide/eye-off-icon').then(module => ({ default: module.EyeOffIcon })))
export const FileTextIcon = lazy(() => import('@animateicons/react/lucide/file-text-icon').then(module => ({ default: module.FileTextIcon })))
export const FolderPlusIcon = lazy(() => import('@animateicons/react/lucide/folder-plus-icon').then(module => ({ default: module.FolderPlusIcon })))
export const HistoryIcon = lazy(() => import('@animateicons/react/lucide/history-icon').then(module => ({ default: module.HistoryIcon })))
export const HouseIcon = lazy(() => import('@animateicons/react/lucide/house-icon').then(module => ({ default: module.HouseIcon })))
export const LayersIcon = lazy(() => import('@animateicons/react/lucide/layers-icon').then(module => ({ default: module.LayersIcon })))
export const LightbulbIcon = lazy(() => import('@animateicons/react/lucide/lightbulb-icon').then(module => ({ default: module.LightbulbIcon })))
export const MailIcon = lazy(() => import('@animateicons/react/lucide/mail-icon').then(module => ({ default: module.MailIcon })))
export const MessageCircleIcon = lazy(() => import('@animateicons/react/lucide/message-circle-icon').then(module => ({ default: module.MessageCircleIcon })))
export const MicIcon = lazy(() => import('@animateicons/react/lucide/mic-icon').then(module => ({ default: module.MicIcon })))
export const PanelLeftIcon = lazy(() => import('@animateicons/react/lucide/panel-left-icon').then(module => ({ default: module.PanelLeftIcon })))
export const PencilIcon = lazy(() => import('@animateicons/react/lucide/pencil-icon').then(module => ({ default: module.PencilIcon })))
export const PhoneIcon = lazy(() => import('@animateicons/react/lucide/phone-icon').then(module => ({ default: module.PhoneIcon })))
export const PlugIcon = lazy(() => import('@animateicons/react/lucide/plug-icon').then(module => ({ default: module.PlugIcon })))
export const SendIcon = lazy(() => import('@animateicons/react/lucide/send-icon').then(module => ({ default: module.SendIcon })))
export const SquarePenIcon = lazy(() => import('@animateicons/react/lucide/square-pen-icon').then(module => ({ default: module.SquarePenIcon })))
export const UsersIcon = lazy(() => import('@animateicons/react/lucide/users-icon').then(module => ({ default: module.UsersIcon })))
